audiconnect/audi_connect_ha

custom_components/audiconnect/audi_connect_account.py
custom_components/audiconnect/audi_services.py
custom_components/audiconnect/dashboard.py

Confirmed working sensor. I've also tried activating climatisation without luck. Disabling it works though.

Facilitating for Climatisation

---

custom_components/audiconnect/audi_services.py

Fixes #77 and maybe #71 #54 #63
The updated endpoint references `NA` so these changes may be applicable in other regions than just `US`, but I have no way to test that.

Fix OpenID configuration endpoint and client ID in US region

---

custom_components/audiconnect/audi_api.py
custom_components/audiconnect/audi_connect_account.py
custom_components/audiconnect/audi_models.py
custom_components/audiconnect/audi_services.py
custom_components/test.py

I check the behaviour of the current app and adopted the login procedure for Germany.
Besides the login, I only tested queries. Actions like preheating are untested.
The URL for get_vehicle_information() has changed and provides less information.

New login procedure from Android myAudi v4.5.0

---

custom_components/audiconnect/audi_services.py

My system could no longer log in because the HTML response from the Audi server no longer contained static form data. This is now apparently created dynamically by a js.
I created a fix that extracts the required data from the js.

Fix for login using js to create form data

---

custom_components/audiconnect/translations/pt-BR.json

Please, add Brazilian Portuguese Translation

Add Brazilian Portuguese Translation

---

custom_components/audiconnect/audi_services.py

Fix set_battery_charger w/o timer (#134)

---

readme.md

OCD-type edits for current Home Assistant terminology, and consistency.

Minor README updates

---

custom_components/audiconnect/audi_connect_account.py
custom_components/audiconnect/const.py
custom_components/audiconnect/dashboard.py

Add individual door/window entity so that user can show more accurate status on the dashboard

[Add] Individual door/window entity

---

custom_components/audiconnect/audi_api.py
custom_components/audiconnect/audi_services.py

New secrect for X_QMAuth and new user agent based on myAudi-Android/4.13.0 (Build 800238275.2210271555) Android/11

X_QMAuth and user agent update (myAudi-Android 4.13.0)

---

custom_components/audiconnect/audi_services.py

Tested and fixes #169 and #168

Update API URLs (#1)

---

custom_components/audiconnect/audi_connect_account.py
custom_components/audiconnect/audi_entity.py
custom_components/audiconnect/audi_services.py
custom_components/audiconnect/device_tracker.py

- Fix: maxChargeCurrent eq 0, actualChargeRate eq 0, chargingPower eq 0
- Removed error message when a feature is detected as unavailable

Fixed reading charge properties eq 0 and removed unnecessary error messages

---

.github/workflows/validate.yml

Github flow to validate this meets HACS requirements and in turn some of home assistant.  I will start creating PRs to fix items that currently aren't valid in this repo.  List is here: https://github.com/cdnninja/audi_connect_ha/actions/runs/6599419119
Right now once this merges it will show errors on future PRs, it doesn't stop merges but makes us aware.

chore:  HACS Validations

---

custom_components/audiconnect/device_tracker.py

fix: correct sourceType of GPS

---

.github/workflows/lintPR.yaml
.github/workflows/release.yml

Checks PRs for titles that will generate release notes.  Also an action to create releases twice a week.  This helps control "beta" release as gives time for larger testing before it releases.  Also gives easy titles for roll back.

chore: Auto Release

---

custom_components/audiconnect/device_tracker.py

Correct source type for a 2025 HA requirement.

fix: correct sourcetype for GPS

---

custom_components/audiconnect/audi_connect_account.py
custom_components/audiconnect/const.py
custom_components/audiconnect/dashboard.py
custom_components/audiconnect/util.py

fix: parsing error & add adblue sensor

---

custom_components/audiconnect/audi_connect_account.py
custom_components/audiconnect/audi_models.py
custom_components/audiconnect/dashboard.py

Add Primary and Secondary Engine Support

feat: Support primary secondary engine

---

custom_components/audiconnect/audi_connect_account.py
custom_components/audiconnect/audi_models.py
custom_components/audiconnect/dashboard.py

fixing remaining charging time
Added: plugLockState, externalPower, plugledColor
thx to @Ingrimmsch93

Added: plugLockState, externalPower, plugledColor + Fixed remaining charging time

---

.github/workflows/validate.yml

Add a schedule to HACS validate as per https://hacs.xyz/docs/publish/action/

fix:  Add HACS Validate Schedule

---

.github/workflows/inactiveIssues.yml
.github/workflows/release.yml

Creating a bot that comments on old issues and marks as stale.  I plan to set this to close issues after 90 days of inactivity.  However wanting to start with it just commenting on them.  Make sure that works and set the -1 to 90.

chore: inactive issues

---

custom_components/audiconnect/audi_models.py
custom_components/audiconnect/manifest.json

https://github.com/audiconnect/audi_connect_ha/issues/285

fix: remainingChargingTime & Debug audi_models.py

---

custom_components/audiconnect/dashboard.py
custom_components/audiconnect/manifest.json
custom_components/audiconnect/sensor.py

fix: LastUpdate timestamp Bug 299

---

custom_components/audiconnect/config_flow.py

- reference `.const` for `DEFAULT_UPDATE_INTERVAL`, `MIN_UPDATE_INTERVAL`
- set initialized value to default
- if user input is less than minimum, set to minimum

fix: More Refresh Interval Updates

---

custom_components/audiconnect/audi_connect_account.py

fixes https://github.com/audiconnect/audi_connect_ha/issues/297

fix: oil_level Issue 297

---

.github/workflows/inactiveIssues.yml

Reduce time windows for stale items and closure.

chore: reduce stale issues action time

---

custom_components/audiconnect/audi_entity.py

This isn't working yet.  Not errors but doesn't solve the issue of lack of data showing in device info for me.

fix: Device Info Datatype

---

custom_components/audiconnect/audi_models.py

This should help both devs and users being able to read the logs to understand when sensor values are found and appended, or not.
Q4 and e-tron owners are having issues seeing sensors, so this is the first piece to figuring that out.

feat: Enhanced Logging for _tryAppendStateWithTs and _tryAppendFieldWithTs

---

custom_components/audiconnect/audi_connect_account.py

In order to analyse https://github.com/audiconnect/audi_connect_ha/issues/307 I added the possibility to provide debug logs for device_tracker

feat: add device tracker debug log

---

custom_components/audiconnect/audi_connect_account.py

Add entity sun_roof Open & Closed currently we only have closed in HA
fix https://github.com/audiconnect/audi_connect_ha/issues/352

fix: Patch sun roof

---

custom_components/audiconnect/audi_models.py

fix: Too Many Warnings

---

custom_components/audiconnect/audi_connect_account.py

Allows for unsupported window state for the sunRoof.
I haven't had a chance to test this yet with my car. I will do that later today.
@Kolbi if you get a chance to test on yours that would be great.

fix: Any Window Open w/ Unsupported Sunroof

---

.github/workflows/inactiveIssues.yml

Issue Stale/Close Message should match the actions

docs: Issue Stale/Close Message

---

custom_components/audiconnect/audi_connect_account.py
custom_components/audiconnect/dashboard.py

This PR introduces 3 new sensors from the `update_vehicle_climater` data.
- Remaining Climatisation Time (`int`) _minutes_
- Displays the remaining minutes for climatisation when running
- Park Time (`datetime`) _timestamp_
- Displays when the vehicle was last parked
- Glass Surface Heating (`bool`) _binary sensor - running_
- Displays if glass surface heating is active or not during climatisation
Other Changes:
- Unified `update_vehicle_climater` debugging with `update_vehicle_position` debugging
- Redacted vin

feat: More Climater Data

---

custom_components/audiconnect/__init__.py

- info > debug
- Added start logging

fix: Logging for "__init__"

---

custom_components/audiconnect/audi_account.py

- Cleaned up logging form `info` to `debug`
- Better logging text

fix: Logging for "Refresh Cloud Data"

---

custom_components/audiconnect/audi_connect_account.py
custom_components/audiconnect/audi_services.py

- Added logging to show when service login is requested and started

fix: Logging for "Login"

---

custom_components/audiconnect/audi_models.py
custom_components/audiconnect/audi_services.py

- Reducing logging to make them more readable. 
- Removing duplicate vehicle data return.

fix: Logging for "VehicleDataResponse"

---

.github/ISSUE_TEMPLATE/bug_report.md

This would be helpful as users typically forget to include these details.

docs: Request Vehicle Details in Issue Template

---

custom_components/audiconnect/audi_connect_account.py
custom_components/audiconnect/audi_models.py
custom_components/audiconnect/dashboard.py

Added the entity target SOC as asked here: https://github.com/audiconnect/audi_connect_ha/issues/404

feat: add target SOC

---

custom_components/audiconnect/audi_models.py

- Added logging for `appendDoorState` & `appendWindowState`
- Removed a duplicate line in `appendDoorState`

fix: Logging for `appendDoorState` & `appendWindowState`

---

custom_components/audiconnect/audi_account.py

Corrects warning around async_forward_entry_setup.  #441

fix: async_forward_entry_setup errors

---

custom_components/audiconnect/audi_models.py
custom_components/audiconnect/util.py

Potentially solves #263  Someone with actually data for this needs to test though. I don't think my car has this data, errors are gone now for me.

fix: error when window or door data missing

---

custom_components/audiconnect/config_flow.py
custom_components/audiconnect/const.py
readme.md

feat: Radio button for region

---

custom_components/audiconnect/audi_connect_account.py

Preheater is giving 502 error and not resolving for most. Moving to disable after first instance. Will check again after restart.

fix: Preheater 502

---

custom_components/audiconnect/audi_connect_account.py
custom_components/audiconnect/dashboard.py

Change Sensor to BinarySensor.

fix: Door trunk state

---

custom_components/audiconnect/audi_connect_account.py
custom_components/audiconnect/dashboard.py

fix: undo 471 to fix 495

---

custom_components/audiconnect/audi_connect_account.py
custom_components/audiconnect/dashboard.py

* plug_state
* plug_lock_state

fix: Sensors => BinarySensors

---

custom_components/audiconnect/audi_services.py

- Fixes functionality for locking/unlocking for US/EU
_Note: Cloud data may not update in time. Fix coming_
- Adds `host` as optional argument for `_get_vehicle_action_header`

fix: Locking

---

custom_components/audiconnect/audi_services.py

Fixes the `start climate control` action as well as the execute vehicle action `stop climatisation` for the EU API 0.

fix: Climate Control: EU/API 0

---

custom_components/audiconnect/manifest.json
info.md

Information was out of date. Open to discussion on this one.

fix: update `info.md`

---

custom_components/audiconnect/audi_connect_account.py

Added guidance for the user to check the myAudi service for updated terms and conditions upon Login Failure.

fix: Check Terms and Conditions

---

custom_components/audiconnect/translations/fi.json

Add Finnish translation. 
Full thanks and credit to @salasami!

fix: Add Finnish Translation

---

custom_components/audiconnect/__init__.py

Doesn't check if data exists just deletes.   So if the car still has data coming from the API it will readd on next startup.

feat: allow deleting cars
