custom_components/audiconnect/__init__.py, readme.md
Hack this integration to work for US-based Audi vehicles. May break configurations for people who erroneously set 'region' (which appears otherwise unused) to some random value, but can be fixed by simply removing/overriding the configuration variable. 
This has been tested on a single US-based Audi car.
=> Add support for monkey patching the Audi account region.

custom_components/test.py
Since logins are now split and you must provide US as a parameter in order to use v1 login, this simplifies testing. Additionally, remove unused import
=> Add country parameter to the test script.

custom_components/audiconnect/audi_connect_account.py
When you have an order vehicle in your audi connect account, this vehicle has no valid vin. Therefore, checking whether the `vin` is `None` when adding a new vehicle is required to exclude order vehicles from being added. WIthout this fix, the integration fails on setup of the account (within HA). Using the test script, the application fails with an exception.
The propsed fix assures that if the vin is None (which should only occur for order vehicles where no actions can be performed anyway) the vehicle is not considered further.
Was tested using the test script as well as within HA directly.
=> check if vin of vehicle is None when adding since order vehicles have no vin

custom_components/audiconnect/audi_entity.py, custom_components/audiconnect/device_tracker.py
many log entries are shows for the different attributes and entities populated due to the deprication of device_state_attributes.
=> Adapting to extra_state_attributes instead of device_state_attributes

custom_components/audiconnect/dashboard.py
Fix incorrect icon name for outdoor temperature
=> Fix incorrect icon name for outdoor temperature

custom_components/audiconnect/audi_services.py
Change start climatisation command to work with Audi E-Tron.
I don't know whether these changes will break this command for other models. For my Audi eTron 2019 it is required to add this to the payload, otherwise the request is rejected by the car. I have set the temperature to 294 deg K => 21 deg C.
=> Fix start_climatisation for Audi e-tron

custom_components/audiconnect/audi_account.py, custom_components/audiconnect/audi_connect_account.py, custom_components/audiconnect/audi_services.py, custom_components/audiconnect/services.yaml, readme.md
The XML based request was no longer working for my 2019 e-tron. Changed
the request to JSON.
Added a new "start_timed_charger" service call which switches the car
from "immediate" charging to "timer". The regular "start_charger" service is
able to switch from "timer" charging back to "immediate".
Note the "stop_charger" action does not work for my car - the request is
accepeted by the Audi server, queued for delivery to the car and
fetched, but the car appears to ignore the request and does not stop
charging.
Resolves #93
Signed-off-by: Matt Redfearn <matt.redfearn@gmail.com>
=> Change charge mode to JSON. Add support for timer charging

custom_components/audiconnect/audi_api.py, custom_components/audiconnect/audi_connect_account.py, custom_components/audiconnect/audi_services.py
The latest version of the Android myAudi app v4.6.0 uses a different secret for the Hmac for X_QMAuth value.
Furthermore I updated and unified the X-App-Version and User-Agent header (fixes #123).
The refresh of the access token failed after about 14hrs because the new refresh_token was not stored. Therefore, a password login was required and performed every 14 hours.
This is fixed now and everything should be token based.
=> Adjusted login to match Android app 4.6.0 (Hmac secret for X_QMAuth)

custom_components/audiconnect/audi_api.py, custom_components/audiconnect/audi_services.py
New secrect for X_QMAuth and new user agent based on myAudi-Android/4.9.2 (Build 800237696.2205091738) Android/11
=> Fix rejected/forbidden client error due to old X_QMAuth

readme.md
The current readme indicated that "US" should be the region code for all North American cars, however this does not work for Canadian users, so I updated the docs to include both US and CA as valid country codes.
=> Updated readme to clarify country codes for US/Canada

custom_components/audiconnect/__init__.py
Performed update inline with https://developers.home-assistant.io/blog/2022/10/14/deprecate-unit-system/
=> Remove deprecated IMPERIAL_SYSTEM check and update to new syntax

custom_components/audiconnect/audi_connect_account.py
Login time should be initialized as `0` instead of the current time to prevent the use of tokens that might have expired due to the logic behind fetching new tokens.
The issue lies in that upon startup of the module, [the elapsed time](https://github.com/woopstar/audi_connect_ha/blob/7e602375015f702b774206be3f1c286479b795d3/custom_components/audiconnect/audi_connect_account.py#L100) is `elapsed_sec = time.time() - self._logintime`, which means upon startup the token has yet not expired in the module, but it can actually be expired already.
Fixes #175
=> Set logintime to 0

custom_components/audiconnect/manifest.json, hacs.json
Integration type is required by HA now. 
HACS.json shouldn't have domains.  This isn't a valid key as per: https://hacs.xyz/docs/publish/start/#hacsjson
These corrections are detected by #208
=> fix: Added integration type to manifest

custom_components/audiconnect/audi_connect_account.py
#55 and #87 - 2 door coupe incorrectly reports rear doors and windows open. This change caters for status "0", which appears to mean unavailable/unsupported.
Very limited testing - it works OK for me, but I've no idea how it will work for you!
=> Fix doors and windows for 2 door coupe

custom_components/audiconnect/audi_services.py
Fixes URL issues for US region users, while still retaining the old URL for non-US users.
This is a replacement for #203, which breaks the URL for non-US users.
=> fix: Integration fails to setup

.github/workflows/inactiveIssues.yml
Auto close issues after 30 days of being tagged stale.   Also corrected message variable to align to the config.  No rush to merge this but thought I would put it in place.   It won't do anything until 30 days from first tags which started just a few days ago. 
This is long lead times on issues but gives us time to reply as well to users.
=> chore:  auto close issues

custom_components/audiconnect/audi_services.py
At least for me in the US, I have to use the `na` endpoint. Found this by proxying my app and seeing this instead. Previously I was getting 401 unauthorized in my logs and essentially no data back.
Confirmed I'm now getting all expected entities:
=> fix: update *.bff.cariad.digital endpoints for different regions

custom_components/audiconnect/__init__.py, custom_components/audiconnect/audi_account.py, custom_components/audiconnect/config_flow.py, custom_components/audiconnect/strings.json, custom_components/audiconnect/translations/de.json, custom_components/audiconnect/translations/en.json, custom_components/audiconnect/translations/nb.json, custom_components/audiconnect/translations/nl.json, custom_components/audiconnect/translations/pt-BR.json
This update introduces several enhancements and fixes aimed at improving the integration's configuration flexibility and efficiency in polling mechanisms.
- **Configurable Scan Interval**: Integration of `OptionsFlowHandler` allows users to adjust the scan interval via the `Configure` menu, enhancing user control.
- **Efficient Polling**: Adoption of `async_track_time_interval` for polling initiation at startup removes the need for manual scheduling in `AudiAccount.update`, streamlining the update process.
- **Localization Updates**: Made updates to strings and translations to ensure clarity and accessibility.
- **Restart Requirement**: Changes necessitate a system restart to take effect. This requirement is detailed in the `data_description` within translations, ensuring users are …
=> feat: Refresh Interval Options

custom_components/audiconnect/audi_account.py, custom_components/audiconnect/strings.json, custom_components/audiconnect/translations/de.json, custom_components/audiconnect/translations/en.json, readme.md
Introduces the `audiconnect.refresh_cloud_data` service call. The service leverages an existing backend function, now made accessible through the Home Assistant UI. It's designed to update vehicle data from the cloud for all vehicles linked to an account **without** initiating a vehicle-side refresh.
Given some limitations with the "Refresh Vehicle Data" functionality, this service call provides a workaround by allowing users to manually trigger data updates. It's particularly useful for users who prefer to extend the default refresh interval significantly and wish to manually request updates at specific moments, such as after starting climate control or during periods of inactivity.
- Functionality: Updates data for all vehicles from the cloud, mirroring the action performed at …
=> feat: New Service - Refresh Cloud Data

custom_components/audiconnect/strings.json, custom_components/audiconnect/translations/de.json, custom_components/audiconnect/translations/en.json, readme.md
Since the `update` (refresh_cloud_data) service is called after vehicle actions automatically, we shouldn't mention the user needs to do this manually.
=> fix: Documentation Cleanup

custom_components/audiconnect/audi_models.py
I find the debug logs difficult to read due to the same data over and over ever scan.  This reduces that.
=> fix: Reduce duplicate debug logs

custom_components/audiconnect/audi_api.py
Audi API Latency can cause the current 10 second timeout to repeatedly fail, while a longer timeout succeeds. Extended latency has been seen in Audi App and HA recently.
=> fix: API Timeout Increase

custom_components/audiconnect/__init__.py, custom_components/audiconnect/audi_account.py, custom_components/audiconnect/dashboard.py, custom_components/audiconnect/sensor.py
- As pointed out by issue #342 the unit of measurement can't be adjusted from the front end. 
- This update allows the use of "Unit of measurement" from the front end to convert values on the fly.
- Updating sensors to use `native_unit_of_measurement` and `native_value`.
- `unit_system` is no longer needed. Removing all instances throughout the integration.
- Last_Update state should not be a string
=> fix: Native unit of measurement

custom_components/audiconnect/audi_account.py
fix for async_add_job being deprecated in HA 2025.4
> async_run_job and async_add_job are deprecated and will be removed in Home Assistant 2025.4. This deprecation does not apply to the sync API add_job method, which is not planned to be removed.
> 
> Instead, it's more efficient to use one of the other job methods, as the method of calling the job does not ever have to be worked out:
> 
> If the callable is a coroutine function running from a config entry: entry.async_create_background_task, entry.async_create_task
> 
> If the callable is a coroutine function running from another place: hass.async_create_background_task, hass.async_create_task
> 
> If the callable should run in the executor: hass.async_add_executor_job
=> fix: async_add_job will be deprecated in HA 2025.4

custom_components/audiconnect/binary_sensor.py, custom_components/audiconnect/dashboard.py, custom_components/audiconnect/sensor.py
This PR categorizes vehicle sensors into two distinct categories: "Sensor" and "Diagnostic", to improve the clarity and organization of the device view in the Audi Connect integration for Home Assistant. This separation is aimed at enhancing user experience by distinguishing between immediate vehicle states and diagnostic or long-term information.
Currently, all vehicle sensors are grouped together, making it difficult to quickly identify critical or short-term state information from long-term diagnostics or static details. This reorganization ensures a cleaner interface and more intuitive navigation for users.
- **Sensor Category**: This is reserved for real-time or short-term information crucial for daily vehicle operation. It includes but is not limited to:
- Broad Lock states
- …
=> feat: Diagnostic sensors

custom_components/audiconnect/audi_connect_account.py
The `sunRoof` should be treated as a window.
#358 fixed the sunroof becoming unavailable, but during testing showed it was always returning `Open`. This fixes that and groups it with the other windows, following the same logic.
- Moving `sun_roof` and `sun_roof_supported` to be grouped with the windows in `audi_connect_account.py`
- Using same logic as other windows (It is defined with the other windows in `audi_models.py > appendWindowState`)
- Updated `any_window_open` to also check the sunroof
_Tested and working as expected_
=> fix: Treat SunRoof as Window

custom_components/audiconnect/audi_connect_account.py
Intermittent issues with `device_tracker` are reported in #307 . Updated Error logs are pointing to no timestamp being reported. Adding to gracefully handle this scenario. 
I'd prefer to default to the last_update_time timestamp, but maybe in the future on a beta branch. 
Currently using `None` as default and its working for me. Looking at `dashboard.py`, `None` is also used by default for these values there.
https://github.com/audiconnect/audi_connect_ha/blob/master/custom_components/audiconnect/dashboard.py#L298-L326
I've tested hardcoding `None` into both values as below and the tracker is working as expected. It seems so long as lat/lon are provided it will work.
```python
self._vehicle.state["position"] = {
"latitude": resp["data"]["lat"],
"longitude": resp["data"]["lon"], …
```
=> fix: Handle Device_Tracker missing timestamp gracefully

custom_components/audiconnect/audi_connect_account.py, custom_components/audiconnect/util.py
Certain vehicles are reporting different timestamp formats for different sensors. The impacts might be the vehicle status report not updating. This could be the reason the Q4 and e-tron aren't working.
This PR attempts to parse the timestamps. 
error in log:
```2024-04-12 06:05:50.056 ERROR (MainThread) [custom_components.audiconnect.audi_connect_account] Unable to obtain the vehicle status report of WA1BCBFZ7PP070298: '>' not supported between instances of 'str' and 'datetime.datetime'
Traceback (most recent call last):
File "/config/custom_components/audiconnect/audi_connect_account.py", line 495, in update_vehicle_statusreport
self._vehicle.state["last_update_time"] = max(
^^^^
TypeError: '>' not supported between instances of 'str' and 'datetime.datetime'
```
One user's log of …
=> fix: update_vehicle_statusreport

custom_components/audiconnect/audi_connect_account.py
"Secondary Engine Range" is reporting the sensor as Unavailable when value is 0. The sensor should still show as available, but display 0.
```
2024-04-11 06:00:02.276 DEBUG (MainThread) [custom_components.audiconnect.audi_models] Found and appended state with timestamp: name=secondaryEngineRange, tsoff=-2, loc=['fuelStatus', 'rangeStatus', 'value', 'carCapturedTimestamp'], val=0, ts=2024-04-11 04:17:04+00:00
```
The issue is due to python considering "0" as Falsy. We need to specifically check if it is neither `None` or `unsupported`.
_tested and working with this PR_
=> fix: "Secondary Engine Range" Unavailable when 0

custom_components/audiconnect/audi_connect_account.py
Instead of using the last_update_time after charging completes, the new logic will preserve the timestamp of the estimated completion. This ensures that the recorded charging complete time remains unchanged in subsequent updates.
=> fix: Charging Complete Time

custom_components/audiconnect/audi_connect_account.py
"External Power" sensor returns the val of "Unavailable". This leads HA to believe the sensor is unavailable and does not report the sensor as active.
```
2024-04-11 06:00:02.277 DEBUG (MainThread) [custom_components.audiconnect.audi_models] Found and appended state with timestamp: name=externalPower, tsoff=-1, loc=['charging', 'plugStatus', 'value', 'carCapturedTimestamp'], val=unavailable, ts=2024-04-10 22:48:14+00:00
```
This PR corrects this by translating `unavailable` to `Not Ready`.
A lot of these sensors should be changed to binary sensors, but if we go ahead and change them now, the old sensor will remain as a duplicate. We need to figure out migration and/or I think the different entities should have unique ID's so HA can recognize them as the same.
=> fix: External Power `Unavailable`

custom_components/audiconnect/audi_connect_account.py
use `parse_datetime` for the vehicle position timestamp/parktime.
=> fix: Vehicle Position Timestamp

custom_components/audiconnect/audi_connect_account.py, custom_components/audiconnect/audi_models.py, custom_components/audiconnect/audi_services.py, custom_components/audiconnect/dashboard.py, custom_components/audiconnect/sensor.py
This PR brings functionality back to the short term and long term trip data sensors.
The primary issue was the `state` of the sensor returning the full data for the relevant trip which exceeded 255 characters.
State now displays the timestamp from the trip, and attributes have been added to the sensor for the other trip data. Using `get` with defaults to avoid keyerrors.
Tested with hardcoded values known to not be available. Tests show the code handled the keyerrors gracefully. Tested with `None` hardcoded as well and 'null' is properly reported.
=> fix: Trip Data

custom_components/audiconnect/audi_connect_account.py
going back to #254 it looks like no safeguard was in place for `get_trip_data` and this was part of the reason this was disabled. This means repeated 403 responses with every update if a vehicle isn't reporting trip data.
This PR adds a check similar to the other data functions which will check once, and upon 403 will disable support for the service and wont check again until next HA restart.
=> fix: Critical Fix - Trip Data 403

custom_components/audiconnect/audi_services.py
- Reset Trip was displaying the wrong data in the logs. It was duplicating the current trip. Front end data is correct, the log is just reflecting incorrectly. This update fixes that.
=> fix: Logging for "get_tripdata"

custom_components/audiconnect/audi_account.py, custom_components/audiconnect/audi_connect_account.py
`refresh_vehicle_data` is currently returning 403. Similar to other functions, like `get_trip_data` and `get_climater` we should check once and disable further tries until a Home Assistant restart. This not only will prevent a user from over polling a forbidden request, it will also increase responsiveness by not waiting for a response each time.
- Redact VINs
- Redundancy: if we're trying `update()` (Refresh Cloud Data) regardless of the `refresh_vehicle_data` success or failure, we don't need to include it in each response action. It only needs to be called at the end.
- Exception handling for `refresh_cloud_data`
=> fix: More 403 Handling

custom_components/audiconnect/audi_models.py
If the API is returning a `False` value for a sensor, the previous logic for `_tryAppendFieldWithTs` would not append. We need to specifically check `val is not None` and append the value.
This PR should fix that. This new logic is already used in `_tryAppendStateWithTs`, it just never made it into `_tryAppendFieldWithTs` for some reason.
See #383 for more details.
=> fix: False bools are not passed

custom_components/audiconnect/audi_connect_account.py
Instructions have been added to tell the user how to show raw unredacted GPS data in their logs. This will help with debugging so users can confirm if the issue is on the Audi API side, or the integration side.
In `custom_components/audiconnect/audi_connect_account.py` user can modify the commented out logger line to add the unredacted data to their logs. Below is the code block to look for:
```python
#_LOGGER.debug("POSITION - UNREDACTED SENSITIVE DATA: Raw vehicle position data: %s", resp)
```
=> fix: Allow user to show raw position data in logs

custom_components/audiconnect/audi_connect_account.py
Charging mode is displaying in HA as a valid sensor with a value of `unsupported`.
The sensor should not be provided if the vehicle does not support the data point.
=> fix: "Charging Mode" Unsupported

custom_components/audiconnect/audi_connect_account.py, custom_components/audiconnect/audi_models.py
As discussed in #402 we need to check if `remaining_charging_time` is supported using a different method. Since the value only appears in the API output when a vehicle is actually charging, we need to check against car type first. If in a supported car type [hybrid,electric], then we want to return the value, if the value isn't available, then we want to return 0.
_Tested and working as expected with my 2021 Q5 plug-in hybrid. 
Hasn't been tested on a gas only vehicle to see if the respective sensors are removed._
=> fix: Remove Charge Time Display for Gas Vehicles

custom_components/audiconnect/audi_entity.py
Fixes #416 device info for vehicles which don't provide a model.
This will use the following hierarchy for device info `model`:
```vehicle_model > vehicle_name > "Unknown"```
=> fix: No Model Provided

custom_components/audiconnect/audi_connect_account.py, custom_components/audiconnect/audi_models.py, custom_components/audiconnect/dashboard.py
Added support for `roofCover` as window as suggested in #359 .
`roofCover` is unsupported for my vehicle. Results were as expected during testing:
- The sensor is not shown in HA as the `roofCover` is listed as `unsupported` in my vehicle data response.
- No other adverse effects were observed.
Further testing would be required by a user who has this data point available for their vehicle to confirm it is working as expected. As we don't know a user with this data point, I suggest reviewing/merging this PR and wait for feedback when available.
=> fix: Support `roofCover`

custom_components/audiconnect/audi_models.py
Add mapping for climatisation state for 2024 Q4
=> fix: Climatisation State for 2024 Q4

.github/ISSUE_TEMPLATE/bug_report.md, custom_components/audiconnect/audi_connect_account.py
We should disable services that return a 404 error. This will decrease the number of polling errors if an endpoint is dead.
Additional Note: Do we really want 502 to disable services? Couldn't a bad gateway be temporary? This could be the reason GPS locations aren't consistently updated over time until an HA reboot?
=> fix: Disable Services w/ 404 Error

custom_components/audiconnect/audi_connect_account.py
Adds `_LOGGER.warning` for 502 Error.
Example:
```
PREHEATER: ClientResponseError with status 502 while updating preheater for VIN: *************8211. This issue may resolve in time. If it persists, please open an issue.
```
=> fix: 502 Logging

custom_components/audiconnect/audi_api.py
Fixes #488
It seems the async_timeout is banned and caused issues anyway, so switching to asyncio seems to work well. Login is possible after this fix and following errors should be gone:
```
Logger: custom_components.audiconnect.audi_connect_account
Quelle: custom_components/audiconnect/audi_connect_account.py:90
Integration: Audi Connect (Dokumentation, Probleme)
Erstmals aufgetreten: 2. November 2024 um 20:10:23 (106 Vorkommnisse)
Zuletzt protokolliert: 09:18:47
LOGIN: Login to Audi service failed: 'Timeout' object does not support the context manager protocol
```
=> fix: async_timeout preventing login

custom_components/audiconnect/audi_connect_account.py, custom_components/audiconnect/const.py, custom_components/audiconnect/dashboard.py
The Audi connect API returns a 204 HTTP code, when the vehicle is in use.
This PR is using this, to update a `is_moving`  binary sensor to indicate the motion of the car. 
If the vehicle is used, the other values aren't updated. So the information is essential.
Changes:
- custom_components/audiconnect/const.py
- `is_moving` has been added to the RESOURCES list
- custom_components/audiconnect/dashboard.py
- The new binary sensor `is moving` has been added.
-  custom_components/audiconnect/audi_connect_account.py
- added the functions to add the new sensor to the dashboard
-  set is_moving to true when receiving a HTTP 204 on the position API call.
-  reset it to false, when receiving a successful position update.
=> feat: is_moving sensor indicates if the vehicle is used

.pre-commit-config.yaml, custom_components/audiconnect/config_flow.py
fixing deprecation warning of config_entry
hass printed out a warning when opening the configuration flow:
Detected that custom integration 'audiconnect' sets option flow config_entry explicitly
and stated that the support will be removed in 2025.12.
The warning was removed by reducing the scope of the class variable config_entry to _config_entry.
=> fix: config entry deprecated warning

custom_components/audiconnect/audi_services.py
Fixes the `execute_vehicle_action` > `Lock`/`Unlock`.
_This fix is currently only available in the US. 
We will extend the fix to the EU once we receive input from a user in that region who has remote door lock capabilities and can capture the request_
=> fix: Lock/Unlock Service (US)

custom_components/audiconnect/audi_services.py
- Fixes the `Execute Vehicle Action` > `Stop Climatisation` service.
- Deprecated the `execute_vehicle_action` > `Start Climatisation (Legacy)` service. Raise exception added to point users to use the `Start Climate Control` service call instead.
- Check Request Succeeded is not yet implemented for API Level 1. Fix coming soon.
=> fix: `execute_vehicle_action` > `stop_climatisation` 

custom_components/audiconnect/dashboard.py
Device Class of `MOTION` gives values of `Detected` or `Clear`. 
Device Class of `MOVING` gives values of `Moving` or `Not moving`.
For the `Is moving` binary sensor, `MOVING` is a better fit.
=> fix: `Is moving` sensor should be `MOVING` device class

custom_components/audiconnect/audi_services.py
Fixes `Execute Vehicle Action` > `Start Charger` & `Start timed Charger` only.
- Currently there is no check to see if the request succeeded before running the refresh cloud data service. This is on the list of fixes to come.
- You can workaround this by adding a delay (~10-30s) in your automation/script and then running a `refresh cloud data` action.
- Setting the charger schedule is a separate action which we will work on for a future release.
- `Stop Charger` is deprecated and will be removed in a future release.
Thanks to @thomas-hass for leading the "charge" and finding a fix for this.
=> fix: Fix Execute Vehicle Action > `Start Charger` & `Start timed Charger`

readme.md
- Added warning about excessive use/abuse of the integration.
- Added tables for `Configuration` and `Options`.
- Removed picture from `Configuration` to reduce maintenance.
- Update terminology to align with HA documentation for `Service Actions`.
- Remove note about `S-PIN` for `Start Climate Control`. It's not required for this service action.
- Updated badge URL.
=> docs: Update `README`

custom_components/audiconnect/audi_services.py
When I was attempting to get my car to lock with the integration I was getting a `NoneType has no len()` from the plugin.
This change adds a new exception before hashing the pin to make sure the pin has a value, this will allow for better feedback to the user in the logs of home assistant.
=> feat: Adding exception when attempting actions where sPin is required and none is provided

custom_components/audiconnect/dashboard.py, custom_components/audiconnect/sensor.py
This makes distance items like mileage show as rounded number instead of two decimals (which are always `.00` and useless)
=> fix: Set suggested display precision to 0 for distance items

custom_components/audiconnect/audi_account.py, custom_components/audiconnect/audi_connect_account.py, custom_components/audiconnect/audi_services.py, custom_components/audiconnect/const.py, custom_components/audiconnect/services.yaml, custom_components/audiconnect/strings.json, custom_components/audiconnect/translations/en.json
Add new Home Assistant service `audiconnect.set_target_soc` that allows users to set the target state of charge (battery percentage) for their Audi electric/hybrid vehicles.
- Add `set_target_state_of_charge()` method in `AudiService` class
- Add corresponding method in `AudiConnectAccount` for error handling
- Register new service in `AudiAccount` with proper schema validation
- Add service configuration in `services.yaml` with UI controls
- Add `CONF_TARGET_SOC` constant for service parameter
- Uses Cariad BFF API endpoint `/charging/settings` (API level 1)
- Validates target range 20-100% with proper error handling
- Follows existing service patterns and coding standards
- Includes comprehensive logging and exception handling
```yaml
service: audiconnect.set_target_soc
data:
vin: …
```
=> feat: add set_target_soc service for battery charge level control

.gitignore, custom_components/audiconnect/audi_connect_account.py, custom_components/audiconnect/audi_models.py, custom_components/audiconnect/const.py, custom_components/audiconnect/dashboard.py
This PR addresses issue #587 by fixing the existing `charging_mode` sensor and adding a new `charging_type` sensor for better charging configuration visibility.
- Issue #587 requested ability to detect and change charging modes
- Investigation revealed `charging_mode` sensor was reading wrong API field, showing "invalid" instead of actual charging mode
- Additional charging type data from API was unused
- Fixed `charging_mode` to read correct API field (`chargeMode`)
- Added new `charging_type` sensor to surface the `chargeType` API field
- Updated field mappings to match API names exactly
**Field Mappings (`audi_models.py`)**
- Updated mapping to use API-consistent field names
- `chargeMode` API field → `chargeMode` internal field
- `chargeType` API field → `chargeType` internal field …
=> feat: improve charging mode sensors and add charging type sensor

custom_components/audiconnect/audi_api.py
`update_vehicle_position` requires an exception to update `is_moving`. this should be refactored. until then, don't log 204 as errors.
=> fix: don't log 204 http-states as errors
